name: PR Builds
on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        jdk: [ 'openjdk11', 'openjdk13' ]
    name: JDK ${{ matrix.jdk }} on ${{ matrix.os }}.
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: actions/cache@v1
        if: runner.os != 'Windows'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/cache@v1
        if: runner.os == 'Windows'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**\pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: mvn -B clean package
